var annotated_dup =
[
    [ "vft", "namespacevft.html", [
      [ "CenterTextAlign", "classvft_1_1CenterTextAlign.html", "classvft_1_1CenterTextAlign" ],
      [ "Character", "classvft_1_1Character.html", "classvft_1_1Character" ],
      [ "CharacterPushConstants", "classvft_1_1CharacterPushConstants.html", "classvft_1_1CharacterPushConstants" ],
      [ "CircularDLL", "classvft_1_1CircularDLL.html", "classvft_1_1CircularDLL" ],
      [ "Contour", "classvft_1_1Contour.html", "classvft_1_1Contour" ],
      [ "Curve", "classvft_1_1Curve.html", "classvft_1_1Curve" ],
      [ "Edge", "classvft_1_1Edge.html", "classvft_1_1Edge" ],
      [ "Font", "classvft_1_1Font.html", "classvft_1_1Font" ],
      [ "FontAtlas", "classvft_1_1FontAtlas.html", "classvft_1_1FontAtlas" ],
      [ "Glyph", "classvft_1_1Glyph.html", "classvft_1_1Glyph" ],
      [ "GlyphCache", "classvft_1_1GlyphCache.html", "classvft_1_1GlyphCache" ],
      [ "GlyphCompositor", "classvft_1_1GlyphCompositor.html", "classvft_1_1GlyphCompositor" ],
      [ "GlyphKey", "classvft_1_1GlyphKey.html", "classvft_1_1GlyphKey" ],
      [ "GlyphKeyHash", "structvft_1_1GlyphKeyHash.html", "structvft_1_1GlyphKeyHash" ],
      [ "GlyphMesh", "classvft_1_1GlyphMesh.html", "classvft_1_1GlyphMesh" ],
      [ "IVulkanTextRenderer", "classvft_1_1IVulkanTextRenderer.html", "classvft_1_1IVulkanTextRenderer" ],
      [ "LeftTextAlign", "classvft_1_1LeftTextAlign.html", "classvft_1_1LeftTextAlign" ],
      [ "LineData", "structvft_1_1LineData.html", "structvft_1_1LineData" ],
      [ "LineDivider", "classvft_1_1LineDivider.html", "classvft_1_1LineDivider" ],
      [ "Outline", "classvft_1_1Outline.html", "classvft_1_1Outline" ],
      [ "PolygonOperator", "classvft_1_1PolygonOperator.html", "classvft_1_1PolygonOperator" ],
      [ "RightTextAlign", "classvft_1_1RightTextAlign.html", "classvft_1_1RightTextAlign" ],
      [ "SdfTessellator", "classvft_1_1SdfTessellator.html", "classvft_1_1SdfTessellator" ],
      [ "SdfTextRenderer", "classvft_1_1SdfTextRenderer.html", "classvft_1_1SdfTextRenderer" ],
      [ "ShapedCharacter", "structvft_1_1ShapedCharacter.html", "structvft_1_1ShapedCharacter" ],
      [ "Shaper", "classvft_1_1Shaper.html", "classvft_1_1Shaper" ],
      [ "TessellationShadersTessellator", "classvft_1_1TessellationShadersTessellator.html", "classvft_1_1TessellationShadersTessellator" ],
      [ "TessellationShadersTextRenderer", "classvft_1_1TessellationShadersTextRenderer.html", "classvft_1_1TessellationShadersTextRenderer" ],
      [ "Tessellator", "classvft_1_1Tessellator.html", "classvft_1_1Tessellator" ],
      [ "TextAlignStrategy", "classvft_1_1TextAlignStrategy.html", "classvft_1_1TextAlignStrategy" ],
      [ "TextBlock", "classvft_1_1TextBlock.html", "classvft_1_1TextBlock" ],
      [ "TextBlockBuilder", "classvft_1_1TextBlockBuilder.html", "classvft_1_1TextBlockBuilder" ],
      [ "TextRenderer", "classvft_1_1TextRenderer.html", "classvft_1_1TextRenderer" ],
      [ "TextSegment", "classvft_1_1TextSegment.html", "classvft_1_1TextSegment" ],
      [ "TriangulationTessellator", "classvft_1_1TriangulationTessellator.html", "classvft_1_1TriangulationTessellator" ],
      [ "TriangulationTextRenderer", "classvft_1_1TriangulationTextRenderer.html", "classvft_1_1TriangulationTextRenderer" ],
      [ "Unicode", "classvft_1_1Unicode.html", "classvft_1_1Unicode" ],
      [ "UniformBufferObject", "classvft_1_1UniformBufferObject.html", "classvft_1_1UniformBufferObject" ],
      [ "VulkanSdfTextRenderer", "classvft_1_1VulkanSdfTextRenderer.html", "classvft_1_1VulkanSdfTextRenderer" ],
      [ "VulkanTessellationShadersTextRenderer", "classvft_1_1VulkanTessellationShadersTextRenderer.html", "classvft_1_1VulkanTessellationShadersTextRenderer" ],
      [ "VulkanTextRenderer", "classvft_1_1VulkanTextRenderer.html", "classvft_1_1VulkanTextRenderer" ],
      [ "VulkanTextRendererDecorator", "classvft_1_1VulkanTextRendererDecorator.html", "classvft_1_1VulkanTextRendererDecorator" ],
      [ "VulkanTimedRenderer", "classvft_1_1VulkanTimedRenderer.html", "classvft_1_1VulkanTimedRenderer" ],
      [ "VulkanTriangulationTextRenderer", "classvft_1_1VulkanTriangulationTextRenderer.html", "classvft_1_1VulkanTriangulationTextRenderer" ],
      [ "VulkanWindingNumberTextRenderer", "classvft_1_1VulkanWindingNumberTextRenderer.html", "classvft_1_1VulkanWindingNumberTextRenderer" ],
      [ "WindingNumberTessellator", "classvft_1_1WindingNumberTessellator.html", "classvft_1_1WindingNumberTessellator" ],
      [ "WindingNumberTextRenderer", "classvft_1_1WindingNumberTextRenderer.html", "classvft_1_1WindingNumberTextRenderer" ]
    ] ]
];